const express = require("express");
const path = require("path");
const cors = require("cors");
const app = express();
app.use(express.static(path.resolve(__dirname, "./client/build")));
app.use(cors());

app.get("/api/products", async (req, res) => {
  res.send(
    [
      {
        "id": 1,
        "name": "Keyboard",
        "brand": "Keycron",
        "image_location": "keyboard.png",
        "price": "1000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 2,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 3,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 4,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 5,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 6,
        "name": "Keyboard",
        "brand": "Keycron",
        "image_location": "keyboard.png",
        "price": "1000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 7,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 8,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 9,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 10,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 11,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 12,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 13,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 14,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 15,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 16,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 17,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 18,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 19,
        "name": "Keyboard",
        "brand": "Keycron",
        "image_location": "keyboard.png",
        "price": "1000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 20,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 21,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 22,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 23,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 24,
        "name": "Keyboard",
        "brand": "Keycron",
        "image_location": "keyboard.png",
        "price": "1000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 25,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 26,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 27,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 28,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 29,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 30,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 31,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 32,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 33,
        "name": "Mouse",
        "brand": "Kensington",
        "image_location": "mouse.png",
        "price": "300",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 34,
        "name": "Kettle",
        "brand": "Hario",
        "image_location": "kettle.png",
        "price": "2000",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 35,
        "name": "Socks",
        "brand": "Carmina",
        "image_location": "socks.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 36,
        "name": "Jerkey",
        "brand": "Renjer",
        "image_location": "jerkey.png",
        "price": "100",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
    ]
  );
});

app.get("/api/cart", async (req, res) => {
  res.send(
    [
      {
        "id": 1,
        "name": "Keyboard",
        "image_location": "keyboard.png",
        "price": "25.44",
        "quantity": 1,
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
      {
        "id": 2,
        "name": "Mouse",
        "image_location": "mouse.png",
        "price": "25.44",
        "quantity": 1,
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae harum voluptas, consequatur rem exercitationem reprehenderit laudantium nostrum magni? Natus repellat harum placeat quidem, beatae fuga ea eos nemo dolore qui!",
      },
    ]
  );
});

const PORT = process.env.PORT || 5002;
app.listen(PORT, () => {
console.log(`Listening on port ${PORT}`);
});